name: Benchmark

on:
  workflow_dispatch: {}
  schedule:
    - cron: "00 00 * * 1"

env:
  CI_RUST_TOOLCHAIN: 1.74.0

jobs:
  benchmark:
    name: Build and Upload Artifacts
    uses: ./.github/workflows/build_xline.yml
    with:
      docker_xline_image: "ghcr.io/xline-kv/build-env:latest"
      binaries: "xline,benchmark"
      additional_setup_commands: |
        docker build . -t ghcr.io/xline-kv/xline:latest
        docker pull datenlord/etcd:v3.5.5
      script_name: "benchmark.sh"
      uploadLogs: false
      uploadBenchmark: true
