name: Validation

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "00 00 * * 1"

jobs:
  validation:
    name: Build and Upload Artifacts
    uses: ./.github/workflows/build_xline.yml
    with:
      docker_xline_image: "ghcr.io/xline-kv/build-env:latest"
      additional_setup_commands: |
        sudo apt-get install -y --force-yes expect
        ldd ./xline
        ldd ./benchmark
        cp ../fixtures/{private,public}.pem .
        docker build . -t ghcr.io/xline-kv/xline:latest
        docker pull gcr.io/etcd-development/etcd:v3.5.5
      binaries: "xline,benchmark"
      script_name: "validation_test.sh"
      uploadLogs: true
